name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.2
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6
  dio: ^4.0.0
  flutter_local_notifications: 9.0.3
  rxdart: ^0.27.7

  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  package_info_plus: ^4.0.2
  open_filex: ^4.3.2
  sensors_plus: ^3.0.2
  share_plus: 4.5.0
  chopper: ^6.1.4
  collection: 1.17.0
  url_launcher: 6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
